name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16, 17, 18]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn
        run: npm i -g yarn

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test --ci
      - name: Codecov
        if: matrix.os == 'ubuntu-latest' && contains(matrix.node, '17')
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
